allow_duplicates: True

dependencies:
  - role: stunnel
    stunnel:
      client: no
      name: "agent_{{ port_forward_name }}"
      accept: "{{ port_forward_agent_port }}"
      connect: "{{ (port_forward_from_host == port_forward_agent_host) | ternary('127.0.0.1', port_forward_from_host) }}:{{ port_forward_from_port }}"
      psk: "{{ port_forward_psk }}"
    when: inventory_hostname == port_forward_agent_host
  - role: stunnel
    stunnel:
      client: yes
      name: "client_{{ port_forward_name }}"
      accept: "{{ port_forward_to_port }}"
      connect: "{{ port_forward_agent_host }}:{{ port_forward_agent_port }}"
      psk: "{{ port_forward_psk }}"
    when: inventory_hostname == port_forward_to_host
