- name: 'Mac | Ensure rinetd'
  homebrew: name=rinetd
  when: ansible_os_family == "Darwin"

- name: Ensure rinetd is running
  shell: pgrep rinetd || /usr/local/sbin/rinetd

- name: rinetd configurations
  template: src=rinetd.conf.j2 dest=/usr/local/etc/rinetd.conf
  notify: Reload Rinetd
